name: Automated Application Runner
on: [workflow_dispatch]

jobs:
  execute-application:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Configure application secrets
      env:
        APP_CONFIG: ${{ secrets.CONFIGURATION }}
      run: |
        echo "$APP_CONFIG" > configuration.ini
        echo "Generated configuration:"
        cat configuration.ini

    - name: Execute application with inputs
      run: |
        yes "y" | head -n 2 | python application.py
        echo "n" | python application.py

    - name: Install tree command
      run: sudo apt-get update && sudo apt-get install -y tree

    - name: Display file structure
      run: |
        echo "=== Current Directory Structure ==="
        tree -a -I '.venv|.git'
        echo "\n=== File Details ==="
        ls -lhR
