name: Run This
on: 
  workflow_dispatch:
    inputs:
      csv:
        description: 'Generate CSV output?'
        required: true
        type: choice
        options: ['true', 'false']
      excel:
        description: 'Generate Excel output?'
        required: true
        type: choice
        options: ['true', 'false']
      mangaupdates:
        description: 'Export to MangaUpdates?'
        required: true
        type: choice
        options: ['false', 'true']

jobs:
  execute-application:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Configure application secrets
      env:
        APP_CONFIG: ${{ secrets.CONFIGURATION }}
      run: |
        echo "$APP_CONFIG" > configuration.ini
        echo "Configuration imported"

    - name: Execute application with inputs
      run: |
        # Create output directory 
        mkdir -p output
        # Set inputs, then exit (blank)
        ( [ "${{ github.event.inputs.csv }}" = 'true' ] && echo 'y' || echo 'n';
          [ "${{ github.event.inputs.excel }}" = 'true' ] && echo 'y' || echo 'n';
          [ "${{ github.event.inputs.mangaupdates }}" = 'true' ] && echo 'y' || echo 'n';
          echo "") | python src/mangadex_follows_exporter.py
        # Move files to output directory (if exist)
        mv follows_*.xlsx output/ || true
        mv follows_*.csv output/ || true
        mv mangaupdates-errors_*.txt output/ || true

    - name: Upload output folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output/
        retention-days: 7
