name: Run This
on: [workflow_dispatch]

jobs:
  execute-application:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Configure application secrets
      env:
        APP_CONFIG: ${{ secrets.CONFIGURATION }}
      run: |
        echo "$APP_CONFIG" > configuration.ini
        echo "Generated configuration:"
        cat configuration.ini

    - name: Execute application with inputs
      run: |
        # set input in order: CSV (y/n), Excel (y/n), MangaUpdates (y/n), then exit (blank)
        (echo "y"; echo "y"; echo "n"; echo "") | python application.py

    - name: Upload output folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output/
